### 순환신경망 RNN <hr>

In [3]:
import torch
import torch.nn as nn

In [4]:
HIDDEN_SIZE = 1
NUM_LAYERS = 1
SQ_LENGTH = 3
BATCH_SIZE = 1

#데이터 및 초기 Hidden State       
input = torch.randn(1, 3, 10)        #  입력데이터(배치크기, 시퀀스 길이, 피처 길이)
h0 = torch.randn(1, 3, 1)          # 히든 초기값

#첫번째 히든스테이트 초기값
rnn = nn.RNN(10,1,1)              # RNN 인스턴스 생성하기

#RNN출력
output, hn = rnn(input, h0)

In [5]:
## 설계 : 다층 RNN, 층 2개
# Input

### 시퀀스 : 한 문장을 구성하는 단어 수
### 피처   : 한 단어를 표현하는 숫자
#입력 초기 텐서들
input = torch.randn(BATCH_SIZE, SQ_LENGTH, 10) # 입력 데이터(배치 크기, 시퀀스 길이, 피처 길이)
h0 = torch.randn(NUM_LAYERS, BATCH_SIZE, HIDDEN_SIZE) # 히든 초기화(배치 크기 1, 시퀀스 길이 1, 은닉 상태 벡터 크기 1) 여기서 배치사이즈는 시퀀스 값을 따라간다. 양방향
                        # 양방향* 층수, 배치크기, 히든 갯수. 
#RNN 인스턴스 
rnn = nn.RNN(10,HIDDEN_SIZE,NUM_LAYERS, batch_first=True) #입력 텐서 차원 : 배치 크기-시퀀스 길이-특성 벡터 크기 순으로 배치됨
                                       #batch_first = false: 차원 순서가 배치 크기 - 시퀀스 길이 - 특성 벡터 크기 순으로 배치. 
# 출력 텐서들
output2, hn2 = rnn(input, h0) # RNN에 입력 데이터, 초기 은닉 텐서 제공하여 계산 수행

In [14]:
print(f'[INPUT DATA]: {input.shape}, DIM = {input.ndim}')
print(output2.shape, hn.shape, output2.ndim)

[INPUT DATA]: torch.Size([1, 3, 10]), DIM = 3
torch.Size([1, 3, 1]) torch.Size([1, 3, 1]) 3


In [ ]:
#Rnn 모델의 속성 출력하기
print(f'[ALL_WEIGHTS] :{len(rnn.all_weights)}')
print(rnn.all_weights)

for name, param in rnn.named_parameters():
    print(f'======>[{name}]\n{param}\n')

In [18]:
print(f'RNN PARAMS')
for name, param in rnn.named_parameters():
    print(f'{name}\n {param}')

RNN PARAMS
weight_ih_l0
 Parameter containing:
tensor([[ 0.8806, -0.5637, -0.1673,  0.5733, -0.8343,  0.7533,  0.0928,  0.7324,
          0.9631,  0.4637]], requires_grad=True)
weight_hh_l0
 Parameter containing:
tensor([[-0.5655]], requires_grad=True)
bias_ih_l0
 Parameter containing:
tensor([-0.5988], requires_grad=True)
bias_hh_l0
 Parameter containing:
tensor([-0.7546], requires_grad=True)


In [13]:

from torchinfo import summary

summary(rnn)

Layer (type:depth-idx)                   Param #
RNN                                      28
Total params: 28
Trainable params: 28
Non-trainable params: 0

In [14]:
## RNN 출력 텐서 output

output.shape, output.ndim

(torch.Size([1, 3, 1]), 3)